using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net.Mime;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SEG.Bff.Web.Models;
using SEG.Bff.Web.Services;
using SEG.WebAPI.Core.Controllers;
using Swashbuckle.AspNetCore.Annotations;

namespace SEG.Bff.Web.Controllers
{
    //[Authorize]
    [Route("api/v1/pessoa")]
    [ApiController]
    public class PessoaController : MainController
    {
        private readonly IPessoaService _pessoaService;

        public PessoaController(IPessoaService pessoaService)
        {
            _pessoaService = pessoaService;
        }

        //[HttpPost]
        //[Route("pessoa/Adicionar")]
        //public async Task<IActionResult> AdicionarPessoa(PessoaDTO pessoa)
        //{

        //    //if(pessoa.nrcgccpf.ToString().Length < 11)
        //    //{
        //    //    AdicionarErroProcessamento("CPF informado está incompleto!");
        //    //    return CustomResponse();
        //    //}

        //    // Comentado por enquanto
        //    //return CustomResponse(await _pessoaService.AdicionarPessoa(pessoa));
        //}

        private class Profissao {
            public int  codigo { get; set; }
        public string nome { get; set; }
        public string codigoCnae { get; set; }
        }


        [SwaggerOperation(summary: "Lista de Profissão", description: "Retorna a lista de profissões habilitadas de um segurado")]
        [Consumes(MediaTypeNames.Application.Json)]
        [Produces(MediaTypeNames.Application.Json)]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Profissao>), description: "Retorna a lista de profissões")]
        [SwaggerResponse(statusCode: 400, type: typeof(ValidationProblemDetails), description: "Parâmetros inválidos")]
        [SwaggerResponse(statusCode: 404, type: typeof(ValidationProblemDetails), description: "Nehuma profissão encontrada")]
        [HttpGet("profissao")]
        public async Task<IActionResult> RetornarListaProfissao()
        { 
            //TODO: Implementar o metodo. Está somente o mock
            var lista = new List<dynamic>
            {
                new{codigo=1,nome="Açougueiro",codigoCnae="ACO001"},
                new{codigo=2,nome="Adestrador",codigoCnae="ADE002"},
                new{codigo=3,nome="Administrador",codigoCnae="ADM003"},
                new{codigo=4,nome="AdministradordeRedeseBancosdeDados",codigoCnae="ADM004"},
                new{codigo=5,nome="Advogado",codigoCnae="ADV005"},
                new{codigo=6,nome="Aeromoça(ComissáriodeBordo)",codigoCnae="AER006"},
                new{codigo=7,nome="AgenciadordePropaganda",codigoCnae="AGE007"},
                new{codigo=8,nome="AgenteAdministrativo",codigoCnae="AGE008"},
                new{codigo=9,nome="AgenteComercial",codigoCnae="AGE009"},
                new{codigo=10,nome="AgentedeCompras",codigoCnae="AGE010"},
                new{codigo=11,nome="AGENTEDESERVIÇOSFUNERARIOS",codigoCnae="AGE015"},
                new{codigo=12,nome="AgentedeVendas",codigoCnae="AGE012"},
                new{codigo=13,nome="AgentedeViagem",codigoCnae="AGE013"},
                new{codigo=14,nome="AgentePenitenciário",codigoCnae="AGE014"},
                new{codigo=15,nome="Agrônomo",codigoCnae="AGR015"},
                new{codigo=16,nome="AjudantedeCozinha",codigoCnae="AJU016"},
                new{codigo=17,nome="Alfaiate",codigoCnae="ALF017"},
                new{codigo=18,nome="Almoxarife",codigoCnae="ALM018"},
                new{codigo=19,nome="AnalistadeRH(RecursosHumanos)",codigoCnae="ANA019"},
                new{codigo=20,nome="AnalistadeSegurançadoTrabalho",codigoCnae="ANA020"},
                new{codigo=21,nome="AnalistadeSistemas",codigoCnae="ANA021"},
                new{codigo=22,nome="Antropólogo",codigoCnae="ANT022"},
                new{codigo=23,nome="Aposentado(excetofuncionáriopúblico)",codigoCnae="APO023"},
                new{codigo=24,nome="ÁrbitroDesportivo",codigoCnae="ARB024"},
                new{codigo=25,nome="Arqueólogo",codigoCnae="ARQ025"},
                new{codigo=26,nome="Arquiteto",codigoCnae="ARQ026"},
                new{codigo=27,nome="Arquivista",codigoCnae="ARQ027"},
                new{codigo=28,nome="Arrematadeira",codigoCnae="ARR028"},
                new{codigo=29,nome="Artesão",codigoCnae="ART029"},
                new{codigo=30,nome="ArtistadeCirco",codigoCnae="ART030"},
                new{codigo=31,nome="Ascensorista",codigoCnae="ASC031"},
                new{codigo=32,nome="AssistenteAdministrativo",codigoCnae="ASS032"},
                new{codigo=33,nome="AssistenteComercial",codigoCnae="ASS033"},
                new{codigo=34,nome="AssistenteSocial",codigoCnae="ASS034"},
                new{codigo=35,nome="Astrólogo",codigoCnae="AST035"},
                new{codigo=36,nome="Astrônomo",codigoCnae="AST036"},
                new{codigo=37,nome="AtletaProfissional",codigoCnae="ATL037"},
                new{codigo=38,nome="Ator",codigoCnae="ATO038"},
                new{codigo=39,nome="Atuário",codigoCnae="ATU039"},
                new{codigo=40,nome="Auditor",codigoCnae="AUD040"},
                new{codigo=41,nome="Autônomos",codigoCnae="AUT041"},
                new{codigo=42,nome="AuxiliarAdministrativo",codigoCnae="AUX042"},
                new{codigo=43,nome="AuxiliardeEnfermagem",codigoCnae="AUX043"},
                new{codigo=44,nome="AuxiliardeEscritório",codigoCnae="AUX044"},
                new{codigo=45,nome="AuxiliardeLaboratório",codigoCnae="AUX045"},
                new{codigo=46,nome="AuxiliardeServiçosGerais",codigoCnae="AUX046"},
                new{codigo=47,nome="Avaliador",codigoCnae="AVA047"},
                new{codigo=48,nome="Bailarino",codigoCnae="BAI048"},
                new{codigo=49,nome="Balconista",codigoCnae="BAL049"},
                new{codigo=50,nome="Bancário",codigoCnae="BAN050"},
                new{codigo=51,nome="Barbeiro",codigoCnae="BAR051"},
                new{codigo=52,nome="Bibliotecário",codigoCnae="BIB052"},
                new{codigo=53,nome="Biólogo",codigoCnae="BIO053"},
                new{codigo=54,nome="Biomédico",codigoCnae="BIO054"},
                new{codigo=55,nome="Bolsista",codigoCnae="BOL055"},
                new{codigo=56,nome="BombeiroHidráulico",codigoCnae="BOM056"},
                new{codigo=57,nome="BombeiroMilitar",codigoCnae="BOM057"},
                new{codigo=58,nome="Borracheiros",codigoCnae="BOR058"},
                new{codigo=59,nome="Cabeleireiro",codigoCnae="CAB059"},
                new{codigo=60,nome="Cabista",codigoCnae="CAB060"},
                new{codigo=61,nome="Caçador",codigoCnae="CAÇ061"},
                new{codigo=62,nome="Caixa",codigoCnae="CAI062"},
                new{codigo=63,nome="Caixeiro-viajante",codigoCnae="CAI063"},
                new{codigo=64,nome="Calista(Podólogo)",codigoCnae="CAL064"},
                new{codigo=65,nome="Camareira",codigoCnae="CAM065"},
                new{codigo=66,nome="Camelô",codigoCnae="CAM066"},
                new{codigo=67,nome="Cantor",codigoCnae="CAN067"},
                new{codigo=68,nome="Carpinteiro",codigoCnae="CAR068"},
                new{codigo=69,nome="Carregador",codigoCnae="CAR069"},
                new{codigo=70,nome="Carteiro",codigoCnae="CAR070"},
                new{codigo=71,nome="Cenógrafo",codigoCnae="CEN071"},
                new{codigo=72,nome="Ceramista",codigoCnae="CER072"},
                new{codigo=73,nome="ChefedeLavanderia",codigoCnae="CHE073"},
                new{codigo=74,nome="Cineasta",codigoCnae="CIN074"},
                new{codigo=75,nome="Cinegrafista",codigoCnae="CIN075"},
                new{codigo=76,nome="Cobrador(TransportesColetivos)",codigoCnae="COB076"},
                new{codigo=77,nome="ComandantedeEmbarcações",codigoCnae="COM077"},
                new{codigo=78,nome="ComentaristadeRádio",codigoCnae="COM078"},
                new{codigo=79,nome="ComentaristadeTelevisão",codigoCnae="COM079"},
                new{codigo=80,nome="Comerciante",codigoCnae="COM080"},
                new{codigo=81,nome="Compositor",codigoCnae="COM081"},
                new{codigo=82,nome="Comunicólogo",codigoCnae="COM082"},
                new{codigo=83,nome="Confeiteiro",codigoCnae="CON083"},
                new{codigo=84,nome="Conferente",codigoCnae="CON084"},
                new{codigo=85,nome="ConsultorJurídico",codigoCnae="CON085"},
                new{codigo=86,nome="Contador",codigoCnae="CON086"},
                new{codigo=87,nome="Contínuo(MensageiroouBoy)",codigoCnae="CON087"},
                new{codigo=88,nome="ContramestredeEmbarcações",codigoCnae="CON088"},
                new{codigo=89,nome="Copeira",codigoCnae="COP089"},
                new{codigo=90,nome="Coreógrafo",codigoCnae="COR090"},
                new{codigo=91,nome="CorretordeImóveis",codigoCnae="COR091"},
                new{codigo=92,nome="CorretordeSeguros",codigoCnae="COR092"},
                new{codigo=93,nome="CorretordeTítuloseValores",codigoCnae="COR093"},
                new{codigo=94,nome="Costureiras",codigoCnae="COS094"},
                new{codigo=95,nome="Coveiros",codigoCnae="COV095"},
                new{codigo=96,nome="Cozinheiro",codigoCnae="COZ096"},
                new{codigo=97,nome="Datilógrafo",codigoCnae="DAT097"},
                new{codigo=98,nome="Decorador",codigoCnae="DEC098"},
                new{codigo=99,nome="DefensorPúblico",codigoCnae="DEF099"},
                new{codigo=100,nome="DelegadodePolícia",codigoCnae="DEL100"},
                new{codigo=101,nome="Demonstrador",codigoCnae="DEM101"},
                new{codigo=102,nome="Dentista(Odontólogo)",codigoCnae="DEN102"},
                new{codigo=103,nome="DeputadoEstadual",codigoCnae="DEP103"},
                new{codigo=104,nome="DeputadoFederal",codigoCnae="DEP104"},
                new{codigo=105,nome="Desembargador",codigoCnae="DES105"},
                new{codigo=106,nome="DesenhistaComercial",codigoCnae="DES106"},
                new{codigo=107,nome="DesenhistaIndustrial",codigoCnae="DES107"},
                new{codigo=108,nome="DesenhistaTécnico",codigoCnae="DES108"},
                new{codigo=109,nome="Designer",codigoCnae="DES109"},
                new{codigo=110,nome="Despachante",codigoCnae="DES110"},
                new{codigo=111,nome="DespachanteAduaneiro",codigoCnae="DES111"},
                new{codigo=112,nome="DetetivedePolícia",codigoCnae="DET112"},
                new{codigo=113,nome="DetetiveParticular",codigoCnae="DET113"},
                new{codigo=114,nome="Digitador",codigoCnae="DIG114"},
                new{codigo=115,nome="Diplomata",codigoCnae="DIP115"},
                new{codigo=116,nome="DiretordeEmpresas",codigoCnae="DIR116"},
                new{codigo=117,nome="DiretordeEscolas",codigoCnae="DIR117"},
                new{codigo=118,nome="DiretordeEspetáculosPúblicos",codigoCnae="DIR118"},
                new{codigo=119,nome="DirigentesdaAdministraçãoPública",codigoCnae="DIR119"},
                new{codigo=120,nome="DoLar",codigoCnae="DOL120"},
                new{codigo=121,nome="DomadordeAnimais",codigoCnae="DOM121"},
                new{codigo=122,nome="Dublê",codigoCnae="DUB122"},
                new{codigo=123,nome="Economista",codigoCnae="ECO123"},
                new{codigo=124,nome="EditordeLivros",codigoCnae="EDI124"},
                new{codigo=125,nome="Eletricista",codigoCnae="ELE125"},
                new{codigo=126,nome="Embalador",codigoCnae="EMB126"},
                new{codigo=127,nome="Embalsamador",codigoCnae="EMB127"},
                new{codigo=128,nome="Empilhador",codigoCnae="EMP128"},
                new{codigo=129,nome="Empregado(a)Doméstico(a)",codigoCnae="EMP129"},
                new{codigo=130,nome="Empresário",codigoCnae="EMP130"},
                new{codigo=131,nome="Encanadores",codigoCnae="ENC131"},
                new{codigo=132,nome="Enfermeiro",codigoCnae="ENF132"},
                new{codigo=133,nome="Engenheiro",codigoCnae="ENG133"},
                new{codigo=134,nome="Escritor",codigoCnae="ESC134"},
                new{codigo=135,nome="EscrivãodePolícia",codigoCnae="ESC135"},
                new{codigo=136,nome="Escultor",codigoCnae="ESC136"},
                new{codigo=137,nome="Estagiário",codigoCnae="EST137"},
                new{codigo=138,nome="Estatístico",codigoCnae="EST138"},
                new{codigo=139,nome="Estenógrafo",codigoCnae="EST139"},
                new{codigo=140,nome="Esteticista",codigoCnae="EST140"},
                new{codigo=141,nome="Estilista",codigoCnae="EST141"},
                new{codigo=142,nome="Estivador",codigoCnae="EST142"},
                new{codigo=143,nome="Estoquista",codigoCnae="EST143"},
                new{codigo=144,nome="Estudante",codigoCnae="EST144"},
                new{codigo=145,nome="ExtrativistaFlorestal",codigoCnae="EXT145"},
                new{codigo=146,nome="Farmacêutico",codigoCnae="FAR146"},
                new{codigo=147,nome="Faxineiro",codigoCnae="FAX147"},
                new{codigo=148,nome="Feirante",codigoCnae="FEI148"},
                new{codigo=149,nome="Fiscal",codigoCnae="FIS149"},
                new{codigo=150,nome="Físico",codigoCnae="FIS150"},
                new{codigo=151,nome="Fisioterapeuta",codigoCnae="FIS151"},
                new{codigo=152,nome="Floricultor",codigoCnae="FLO152"},
                new{codigo=153,nome="FoguistadeEmbarcações",codigoCnae="FOG153"},
                new{codigo=154,nome="FoguistadeLocomotivas",codigoCnae="FOG154"},
                new{codigo=155,nome="Fonoaudiólogo",codigoCnae="FON155"},
                new{codigo=156,nome="Fotógrafo",codigoCnae="FOT156"},
                new{codigo=157,nome="Frentista",codigoCnae="FRE157"},
                new{codigo=158,nome="FuncionárioPúblicoCivilAposentado(semIPD)",codigoCnae="FUN158"},
                new{codigo=159,nome="Garagista/Manobrista",codigoCnae="GAR159"},
                new{codigo=160,nome="Garçom",codigoCnae="GAR160"},
                new{codigo=161,nome="Gari",codigoCnae="GAR161"},
                new{codigo=162,nome="Garimpeiro",codigoCnae="GAR162"},
                new{codigo=163,nome="Geógrafo",codigoCnae="GEO163"},
                new{codigo=164,nome="Geólogo",codigoCnae="GEO164"},
                new{codigo=165,nome="Gerente",codigoCnae="GER165"},
                new{codigo=166,nome="GovernadordeEstado",codigoCnae="GOV166"},
                new{codigo=167,nome="GovernantadeHotel",codigoCnae="GOV167"},
                new{codigo=168,nome="Gráfico",codigoCnae="GRA168"},
                new{codigo=169,nome="GuardadeTrânsito",codigoCnae="GUA169"},
                new{codigo=170,nome="GuardaFlorestal",codigoCnae="GUA170"},
                new{codigo=171,nome="GuardaMunicipal",codigoCnae="GUA171"},
                new{codigo=172,nome="GuiadeTurismo",codigoCnae="GUI172"},
                new{codigo=173,nome="Historiador",codigoCnae="HIS173"},
                new{codigo=174,nome="InspetordeEscolas",codigoCnae="INS174"},
                new{codigo=175,nome="InspetordePolícia",codigoCnae="INS175"},
                new{codigo=176,nome="InspetordeTrânsito(CETRIO)",codigoCnae="INS176"},
                new{codigo=177,nome="InstaladordeGás,ÁguaeEsgoto",codigoCnae="INS177"},
                new{codigo=178,nome="InstrumentadorCirúrgico",codigoCnae="INS178"},
                new{codigo=179,nome="Jardineiro",codigoCnae="JAR179"},
                new{codigo=180,nome="Joalheiro",codigoCnae="JOA180"},
                new{codigo=181,nome="Jóquei",codigoCnae="JOQ181"},
                new{codigo=182,nome="Jornaleiro",codigoCnae="JOR182"},
                new{codigo=183,nome="Jornalista",codigoCnae="JOR183"},
                new{codigo=184,nome="Juiz",codigoCnae="JUI184"},
                new{codigo=185,nome="JuizesClassistas",codigoCnae="JUI185"},
                new{codigo=186,nome="Ladrilheiros",codigoCnae="LAD186"},
                new{codigo=187,nome="Lanterneiro",codigoCnae="LAN187"},
                new{codigo=188,nome="Leiloeiro",codigoCnae="LEI188"},
                new{codigo=189,nome="Lixeiro",codigoCnae="LIX189"},
                new{codigo=190,nome="Locutor",codigoCnae="LOC190"},
                new{codigo=191,nome="Maitre",codigoCnae="MAI191"},
                new{codigo=192,nome="Manicure",codigoCnae="MAN192"},
                new{codigo=193,nome="Maquilador",codigoCnae="MAQ193"},
                new{codigo=194,nome="Maquinista",codigoCnae="MAQ194"},
                new{codigo=195,nome="Marinheiro",codigoCnae="MAR195"},
                new{codigo=196,nome="Massagista",codigoCnae="MAS196"},
                new{codigo=197,nome="Matemático",codigoCnae="MAT197"},
                new{codigo=198,nome="Mecânico",codigoCnae="MEC198"},
                new{codigo=199,nome="Médico",codigoCnae="MED199"},
                new{codigo=200,nome="MembrodeOrdensReligiosas",codigoCnae="MEM200"},
                new{codigo=201,nome="MembrodeSeitasReligiosas",codigoCnae="MEM201"},
                new{codigo=202,nome="MembrosdaDefensoriaPública",codigoCnae="MEM202"},
                new{codigo=203,nome="MembrosdoMinistérioPúblico",codigoCnae="MEM203"},
                new{codigo=204,nome="Merendeiras",codigoCnae="MER204"},
                new{codigo=205,nome="MergulhadorProfissional",codigoCnae="MER205"},
                new{codigo=206,nome="MestredeEmbarcações",codigoCnae="MES206"},
                new{codigo=207,nome="MestredeObras",codigoCnae="MES207"},
                new{codigo=208,nome="Meteorologista",codigoCnae="MET208"},
                new{codigo=209,nome="MilitaremGeral",codigoCnae="MIL209"},
                new{codigo=210,nome="MilitarReformado",codigoCnae="MIL210"},
                new{codigo=211,nome="MinistrodeEstado",codigoCnae="MIN211"},
                new{codigo=212,nome="MinistrodeTribunalSuperior",codigoCnae="MIN212"},
                new{codigo=213,nome="Modelista",codigoCnae="MOD213"},
                new{codigo=214,nome="ModelodeModas",codigoCnae="MOD214"},
                new{codigo=215,nome="Montador",codigoCnae="MON215"},
                new{codigo=216,nome="Motoboy",codigoCnae="MOT216"},
                new{codigo=217,nome="MotoristadeTransportedeCargas(Caminhoneiro)",codigoCnae="MOT217"},
                new{codigo=218,nome="MotoristadeTransportedePassageiros(Ônibus,Vans)",codigoCnae="MOT218"},
                new{codigo=219,nome="Museólogo",codigoCnae="MUS219"},
                new{codigo=220,nome="Músico",codigoCnae="MUS220"},
                new{codigo=221,nome="Nutricionista",codigoCnae="NUT221"},
                new{codigo=222,nome="Oceanógrafo",codigoCnae="OCE222"},
                new{codigo=223,nome="OficiaisdasForçasArmadas",codigoCnae="OFI223"},
                new{codigo=224,nome="OficiaisdasForçasAuxiliares",codigoCnae="OFI224"},
                new{codigo=225,nome="OperadordeCâmerasdeTelevisãoeCinema",codigoCnae="OPE225"},
                new{codigo=226,nome="OperadordeComputadores",codigoCnae="OPE226"},
                new{codigo=227,nome="OperadordeMáquinaseAparelhos",codigoCnae="OPE227"},
                new{codigo=228,nome="OperadordeTelemarketing",codigoCnae="OPE228"},
                new{codigo=229,nome="OrientadorEducacional",codigoCnae="ORI229"},
                new{codigo=230,nome="Ortoptista(TécnicoemExercíciosOrtópticos)",codigoCnae="ORT230"},
                new{codigo=231,nome="Ourives",codigoCnae="OUR231"},
                new{codigo=232,nome="Padeiros",codigoCnae="PAD232"},
                new{codigo=233,nome="Padre",codigoCnae="PAD233"},
                new{codigo=234,nome="Patologista",codigoCnae="PAT234"},
                new{codigo=235,nome="Pedagogo",codigoCnae="PED235"},
                new{codigo=236,nome="Pedicure",codigoCnae="PED236"},
                new{codigo=237,nome="Pedreiro",codigoCnae="PED237"},
                new{codigo=238,nome="Pensionista",codigoCnae="PEN238"},
                new{codigo=239,nome="PeritoCriminal",codigoCnae="PER239"},
                new{codigo=240,nome="Pescador",codigoCnae="PES240"},
                new{codigo=241,nome="PilotodeAeronaves",codigoCnae="PIL241"},
                new{codigo=242,nome="PilotosAutomobilísticosProfissionais",codigoCnae="PIL242"},
                new{codigo=243,nome="PintorArtístico",codigoCnae="PIN243"},
                new{codigo=244,nome="PintordeParedes",codigoCnae="PIN244"},
                new{codigo=245,nome="PintordeVeículosMetálicos",codigoCnae="PIN245"},
                new{codigo=246,nome="PolicialCivil",codigoCnae="POL246"},
                new{codigo=247,nome="PolicialFederal",codigoCnae="POL247"},
                new{codigo=248,nome="PolicialMilitar",codigoCnae="POL248"},
                new{codigo=249,nome="PolicialRodoviário",codigoCnae="POL249"},
                new{codigo=250,nome="Porteiro",codigoCnae="POR250"},
                new{codigo=251,nome="PorteirodeEdifício",codigoCnae="POR251"},
                new{codigo=252,nome="Prefeito",codigoCnae="PRE252"},
                new{codigo=253,nome="PreparadoresFísicos",codigoCnae="PRE253"},
                new{codigo=254,nome="Procurador",codigoCnae="PRO254"},
                new{codigo=255,nome="ProdutordeEspetáculosPúblicos",codigoCnae="PRO255"},
                new{codigo=256,nome="Professor",codigoCnae="PRO256"},
                new{codigo=257,nome="ProfissionaisdeArtes",codigoCnae="PRO257"},
                new{codigo=258,nome="ProfissionaldeMarketing",codigoCnae="PRO258"},
                new{codigo=259,nome="ProgramadordeComputadores",codigoCnae="PRO259"},
                new{codigo=260,nome="PromotordeEventos",codigoCnae="PRO260"},
                new{codigo=261,nome="PromotordeJustiça",codigoCnae="PRO261"},
                new{codigo=262,nome="PromotordeVendas",codigoCnae="PRO262"},
                new{codigo=263,nome="Protético",codigoCnae="PRO263"},
                new{codigo=264,nome="Psicanalista",codigoCnae="PSI264"},
                new{codigo=265,nome="Psicólogo",codigoCnae="PSI265"},
                new{codigo=266,nome="Publicitário",codigoCnae="PUB266"},
                new{codigo=267,nome="Químico",codigoCnae="QUI267"},
                new{codigo=268,nome="Radialista",codigoCnae="RAD268"},
                new{codigo=269,nome="Recenseador",codigoCnae="REC269"},
                new{codigo=270,nome="Recepcionista",codigoCnae="REC270"},
                new{codigo=271,nome="RelaçõesPúblicas",codigoCnae="REL271"},
                new{codigo=272,nome="Repórter",codigoCnae="REP272"},
                new{codigo=273,nome="RepresentanteComercial",codigoCnae="REP273"},
                new{codigo=274,nome="Restaurador",codigoCnae="RES274"},
                new{codigo=275,nome="Sacerdote",codigoCnae="SAC275"},
                new{codigo=276,nome="Salva-Vidas",codigoCnae="SAL276"},
                new{codigo=277,nome="Sapateiros",codigoCnae="SAP277"},
                new{codigo=278,nome="SecretáriodeEstado",codigoCnae="SEC278"},
                new{codigo=279,nome="SecretárioMunicipal",codigoCnae="SEC279"},
                new{codigo=280,nome="Secretário(a)",codigoCnae="SEC280"},
                new{codigo=281,nome="Securitário",codigoCnae="SEC281"},
                new{codigo=282,nome="Segurança",codigoCnae="SEG282"},
                new{codigo=283,nome="Senador",codigoCnae="SEN283"},
                new{codigo=284,nome="SERVENTE",codigoCnae="SER284"},
                new{codigo=285,nome="ServentuáriodaJustiça",codigoCnae="SER285"},
                new{codigo=286,nome="ServidorPúblico",codigoCnae="SER286"},
                new{codigo=287,nome="Sociólogo",codigoCnae="SOC287"},
                new{codigo=288,nome="Soldador",codigoCnae="SOL288"},
                new{codigo=289,nome="Sonoplasta",codigoCnae="SON289"},
                new{codigo=290,nome="Supervisores",codigoCnae="SUP290"},
                new{codigo=291,nome="Tabelião",codigoCnae="TAB291"},
                new{codigo=292,nome="Taxista",codigoCnae="TAX292"},
                new{codigo=293,nome="TécnicodeBiologia",codigoCnae="TEC293"},
                new{codigo=294,nome="TécnicodeContabilidade",codigoCnae="TEC294"},
                new{codigo=295,nome="TécnicodeEstatística",codigoCnae="TEC295"},
                new{codigo=296,nome="TécnicodeFundição",codigoCnae="TEC296"},
                new{codigo=297,nome="TécnicodeLaboratório",codigoCnae="TEC297"},
                new{codigo=298,nome="TécnicodeObras",codigoCnae="TEC298"},
                new{codigo=299,nome="TécnicodeRaioX",codigoCnae="TEC299"},
                new{codigo=300,nome="TécnicodeSuporte(Informática)",codigoCnae="TEC300"},
                new{codigo=301,nome="TécnicoDesportivos",codigoCnae="TEC301"},
                new{codigo=302,nome="TécnicoemAdministração",codigoCnae="TEC302"},
                new{codigo=303,nome="TécnicoemAgrimensura",codigoCnae="TEC303"},
                new{codigo=304,nome="TécnicoemAgronomia",codigoCnae="TEC304"},
                new{codigo=305,nome="TécnicoemCiênciasFísicaseQuímicas",codigoCnae="TEC305"},
                new{codigo=306,nome="TécnicoemConstruçãoCivil",codigoCnae="TEC306"},
                new{codigo=307,nome="TécnicoemEdificações",codigoCnae="TEC307"},
                new{codigo=308,nome="TécnicoemEletricidade",codigoCnae="TEC308"},
                new{codigo=309,nome="TécnicoemEletrônica",codigoCnae="TEC309"},
                new{codigo=310,nome="TécnicoemEnfermagem",codigoCnae="TEC310"},
                new{codigo=311,nome="TécnicoemIluminação",codigoCnae="TEC311"},
                new{codigo=312,nome="TécnicoemMecânica",codigoCnae="TEC312"},
                new{codigo=313,nome="TécnicoemMineração",codigoCnae="TEC313"},
                new{codigo=314,nome="TécnicoemNavegação",codigoCnae="TEC314"},
                new{codigo=315,nome="TécnicoemOrtopedia",codigoCnae="TEC315"},
                new{codigo=316,nome="TécnicoemProduçãoAgropecuária",codigoCnae="TEC316"},
                new{codigo=317,nome="TécnicoemQuímica",codigoCnae="TEC317"},
                new{codigo=318,nome="TécnicoemSegurançadoTrabalho",codigoCnae="TEC318"},
                new{codigo=319,nome="TécnicoemTelecomunicações",codigoCnae="TEC319"},
                new{codigo=320,nome="Tecnólogo",codigoCnae="TEC320"},
                new{codigo=321,nome="Telefonista",codigoCnae="TEL321"},
                new{codigo=322,nome="Teólogo",codigoCnae="TEO322"},
                new{codigo=323,nome="TerapeutaOcupacional",codigoCnae="TER323"},
                new{codigo=324,nome="Tintureiro",codigoCnae="TIN324"},
                new{codigo=325,nome="Topógrafo",codigoCnae="TOP325"},
                new{codigo=326,nome="TrabalhadorAgrícola",codigoCnae="TRA326"},
                new{codigo=327,nome="TrabalhadordaConstruçãoCivil",codigoCnae="TRA327"},
                new{codigo=328,nome="TrabalhadordaPecuária",codigoCnae="TRA328"},
                new{codigo=329,nome="TrabalhadordeArtesGráficas",codigoCnae="TRA329"},
                new{codigo=330,nome="TrabalhadordeFabricaçãodeAlimentoseBebidas",codigoCnae="TRA330"},
                new{codigo=331,nome="TrabalhadordeFabricaçãodeCigarroseCharutos",codigoCnae="TRA331"},
                new{codigo=332,nome="TrabalhadordeFabricaçãodePapelePapelão",codigoCnae="TRA332"},
                new{codigo=333,nome="TrabalhadordeFabricaçãodeProdutosTêxteis",codigoCnae="TRA333"},
                new{codigo=334,nome="TrabalhadordeFabricaçãoemBorrachaePlástico",codigoCnae="TRA334"},
                new{codigo=335,nome="TrabalhadordeFabricaçãoemCouro",codigoCnae="TRA335"},
                new{codigo=336,nome="TrabalhadordeFabricaçãoemMadeira",codigoCnae="TRA336"},
                new{codigo=337,nome="TrabalhadordeIndústriaPetroquímica(seemplataforma)",codigoCnae="TRA337"},
                new{codigo=338,nome="TrabalhadordeInstalaçõesdeProcessamentoQuímico",codigoCnae="TRA338"},
                new{codigo=339,nome="TrabalhadordeMineração",codigoCnae="TRA339"},
                new{codigo=340,nome="TrabalhadordeUsinagemdeMetais",codigoCnae="TRA340"},
                new{codigo=341,nome="TrabalhadorFlorestal",codigoCnae="TRA341"},
                new{codigo=342,nome="TrabalhadorMetalúrgico",codigoCnae="TRA342"},
                new{codigo=343,nome="TrabalhadorSiderúrgico",codigoCnae="TRA343"},
                new{codigo=344,nome="Tradutor",codigoCnae="TRA344"},
                new{codigo=345,nome="VENDEDOR",codigoCnae="VEN345"},
                new{codigo=346,nome="Vereador",codigoCnae="VER346"},
                new{codigo=347,nome="Veterinário",codigoCnae="VET347"},
                new{codigo=348,nome="Vidraceiros",codigoCnae="VID348"},
                new{codigo=349,nome="Vigia",codigoCnae="VIG349"},
                new{codigo=350,nome="Vigilante",codigoCnae="VIG350"},
                new{codigo=351,nome="Vitrinista",codigoCnae="VIT351"},
                new{codigo=352,nome="Zootecnista",codigoCnae="ZOO352"},
                new{codigo=353,nome="TATUADOROUPROFISSIONALQUETRABALHAEMLOJASDETATUAGEM",codigoCnae="TAT353"},
                new{codigo=354,nome="BODYPIERCERS(COLOCADORDEPIERCIN)",codigoCnae="TAT354"},
                new{codigo=355,nome="VISTORIADORDEAUTOSE/OUOUTROSRAMOSDESEGURO",codigoCnae="VIS355"},
                new{codigo=356,nome="COMISSÁRIODEAVARIAS",codigoCnae="COM356"},
                new{codigo=1000,nome="PROFISSÃONÃOIDENTIFICADA",codigoCnae="PNI1000"}
            };

            return CustomResponse(lista);
        }

    }
}
